# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.



title: Linjia
description: >- # this means to ignore newlines until "baseurl:"
  Linjia Song.
# baseurl: "/Lin" # the subpath of the site  #bay
url: "https://linjiasong.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile_picture.jpg
#google_analytics: "UA-121636368-3"

header: 
  pages:
    - name: Home
      slug: /
   # - name: CV
   #- name: Research

footer:
  show_powered_by: false
  contact:
    - name: Email
      value: linjiasong@hotmail.com
      link: mailto:linjiasong@hotmail.com
  follow:
    - name: LinkedIn
      link: https://hk.linkedin.com/in/songlinjia


# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
